[MeterBar0]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed0]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar1]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed1]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar2]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed2]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar3]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed3]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar4]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed4]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar5]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed5]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar6]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed6]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar7]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed7]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar8]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed8]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar9]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed9]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar10]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed10]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar11]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed11]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar12]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed12]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar13]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed13]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar14]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed14]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar15]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed15]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar16]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed16]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar17]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed17]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar18]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed18]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar19]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed19]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar20]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed20]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar21]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed21]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar22]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed22]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar23]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed23]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar24]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed24]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar25]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed25]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar26]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed26]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar27]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed27]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar28]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed28]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar29]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed29]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar30]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed30]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar31]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed31]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar32]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed32]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar33]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed33]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar34]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed34]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar35]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed35]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar36]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed36]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar37]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed37]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1
[MeterBar38]
Meter=Shape
Group=GroupBars | GroupDynamicColors
X=6R
Y=242
Shape=Rectangle 0,0,(25*0.16),(-(242-(25*0.16))*[MeasureAudioSmoothed38]-(25*0.16)),((25*0.16)/2) | Fill Color #Color# | StrokeWidth 0
DynamicVariables=1