[Rainmeter]
Update=1000
Author=-HipHopium-
BackgroundMode=2
SolidColor=0,0,0,1
LeftMouseDoubleClickAction=!ToggleConfig "Simple Clean\Settings" "Settings.ini"

[Variables]
@include=#@#Variables.inc
@include2=#@#Language\#Language#.inc

;-------------------------------------------------------------
;-------------------------------------------------------------

[StyleTime]
StringAlign=Center
FontColor=224,208,255
FontFace=Jetbrains Mono
AntiAlias=1

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeasureClock]
Measure=Time
Format=%H:%M

[MeasureDate]
Measure=Time
Format=%A, %d %B %Y.
Substitute=#Date#

;-------------------------------------------------------------
;-------------------------------------------------------------

[MeterClock]
Meter=String
MeterStyle=StyleTime
MeasureName=MeasureClock
FontSize=64
X=130
Y=1
Text="%1"

[MeterDate]
Meter=String
MeterStyle=StyleTime
MeasureName=MeasureDate
FontSize=11
W=366
X=129
Y=105
Text="%1"